version: '3.8'

services:
  userservice:
    build: .
    container_name: userservice_prod
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/userservice_db
      - SPRING_DATASOURCE_USERNAME=devuser
      - SPRING_DATASOURCE_PASSWORD=devsecret
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - postgres_db
      - redis 

  postgres_db:
    image: postgres:15
    container_name: postgres_db_prod
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=userservice_db
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devsecret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine 
    container_name: redis_prod
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  postgres-data:
  redis-data: